URL = "url"
NAME = "name"
ZIP_FILES_DIRECTORY = "./zip_files"
XML_FILES_DIRECTORY = "./xml_files"
DATE_FORMAT = "%Y%m%d"
DOWNLOAD_LINKS_YENOT_BITAN_FULL = "//a[(contains(@href, 'Full'))]"
DOWNLOAD_LINKS_YENOT_BITAN_STORES = "(//a[(contains(@href, 'Stores'))])[1]"
DOWNLOAD_LINKS_VICTORY = "//tr[.//td[contains(text(), 'ויקטורי')] and .//a[contains(@href, 'Full')]]//a"
URL_FILES = './urls.json'
